document.writeln("<html>");
document.writeln("<head>");
document.writeln("	<title>导航</title>");
document.writeln("</head>");
document.writeln("<div>");
document.writeln("	<select name=\'pageselect\' onchange=\'self.location.href=options[selectedIndex].value\' style=\'width:60%\' class=\'select\'>");
document.writeln("                <option selected value=\'\'>==选择访问对象==</option>");
document.writeln("				<option disabled value=\'/\' style=\'color:red\'>版本Ver.1.1.0[禁用]</option>");
document.writeln("				<option disabled style=\'color:red\' value=\'../index.html/\'>[维护]</option>");
document.writeln("				<option value=\'tool/2025.html\'>2025 新年倒计时</option>");
document.writeln("				<option value=\'tool/jsq.html\'>计时器</option>");
document.writeln("				<option value=\'tool/class.html\'>上课模拟器</option>");
document.writeln("				</select>");
document.writeln("");
document.writeln("	<!-- -->");
document.writeln("");
document.writeln("	<hr>");
document.writeln("");
document.writeln("</div>");
document.writeln("");
document.writeln("<!-- -->");
document.writeln("");
document.writeln("<div>");
document.writeln("");
document.writeln("	<select name=\'pageselect\' onchange=\'self.location.href=options[selectedIndex].value\' style=\'width:20%\' class=\'select\'>");
document.writeln("                <option selected value=\'\'>本站服务</option>");
document.writeln("                <option value=\'tool/ceshi.html\'>性能测试</option>");
document.writeln("				</select>");
document.writeln("");
document.writeln("	<select name=\'pageselect\' onchange=\'self.location.href=options[selectedIndex].value\' style=\'width:20%\' class=\'select\'>");
document.writeln("                <option selected value=\'\'>曲靖一中</option>");
document.writeln("                <option value=\'http://ynqjdyzx.com/\'>学校官网</option>");
document.writeln("				</select>");
document.writeln("");
document.writeln("	<select name=\'pageselect\' onchange=\'self.location.href=options[selectedIndex].value\' style=\'width:20%\' class=\'select\'>");
document.writeln("                <option selected value=\'\'>相关信息</option>");
document.writeln("				<option value=\'law.html\'>隐私政策</option>");
document.writeln("				</select>");
document.writeln("");
document.writeln("</div>");
document.writeln("");
document.writeln("</html>");
document.writeln("");
document.writeln("<!-- 控制台 -->");
document.writeln("<script>");
document.writeln("	console.log(\'更新于 %d年%d月%d日\',2024,10,20);");
document.writeln("	console.warn( \'版权所有·侵权必究\' );");
document.writeln("	console.error( \'未经作者许可，禁止转载\' );");
document.writeln("	console.log( \'OS 版本 # 24.10.20\' );");
document.writeln("	console.info( \'隐私协议 \' );");
document.writeln("	console.warn( \'严格遵守国家相关法律法规\' );");
document.writeln("	console.info( \'作者 BGR\' );");
document.writeln("</script>");