document.writeln("");
document.writeln("<div class=\'gg\'>");
document.writeln("");
document.writeln("	<div id=\'box1\' style=\'color:red\'>");
document.writeln("		= 最新公告 =");
document.writeln("	</div>");
document.writeln("	<script>");
document.writeln("		function timingTime(){");
document.writeln("      let start = \'2023-9-11 12:00:00\'");
document.writeln("      let startTime = new Date(start).getTime()");
document.writeln("      let currentTime = new Date().getTime()");
document.writeln("      let difference = currentTime - startTime");
document.writeln("      let m =  Math.floor(difference / (1000))");
document.writeln("      let mm = m % 60  // 秒");
document.writeln("      let f = Math.floor(m / 60)");
document.writeln("      let ff = f % 60 // 分钟");
document.writeln("      let s = Math.floor(f/ 60) // 小时");
document.writeln("      let ss = s % 24");
document.writeln("      let day = Math.floor(s  / 24 ) // 天数");
document.writeln("");
document.writeln("if(day<100) day = \'00\' + day;");
document.writeln("    if(ff<10) ff = \'0\' + ff;");
document.writeln("    if(mm<10) mm = \'0\' + mm;");
document.writeln("    if(ss<10) ss = \'0\' + ss;");
document.writeln("");
document.writeln("      return  \'! 加入2026高考倒计时 !\'");
document.writeln("	  //我部建立已 \' + day + \' 天 \' + ss + \' 时 \' + ff + \' 分 \' + mm +\' 秒");
document.writeln("    }");
document.writeln("    setInterval(()=>{");
document.writeln("      document.getElementById(\'box1\').innerHTML = timingTime()");
document.writeln("    },3000)");
document.writeln("	</script>");
document.writeln("");
document.writeln("</div>");
document.writeln("");
document.writeln("");